### ISSUE TITLE
Alerts not receiving in snmp receiver end

### ISSUE THREAD

**Issue by sanupanji** [maxwo/snmp_notifier#132] opened 2023-02-21 14:20 UTC
**What did you do?**
I am using Prometheus, Grafana, Alertmanager stack to monitor my EDB postgres installed in bare metal k8s cluster.

I am receiving alerts in alert manager with below configuration.

```global:
  resolve_timeout: 5m
  http_config:
    follow_redirects: true
  smtp_hello: localhost
  smtp_require_tls: true
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
route:
  receiver: snmp_notifier
  group_by:
  - job
  continue: false
  routes:
  - receiver: "null"
    match:
      alertname: Watchdog
    continue: false
  - receiver: snmp_notifier
    continue: false
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
receivers:
- name: "null"
- name: snmp_notifier
  webhook_configs:
  - send_resolved: true
    http_config:
      follow_redirects: true
    url: http://snmpnotifier.cnp-monitoring.svc.cluster.local:9464/alerts
    max_alerts: 0
templates:
- /etc/alertmanager/config/*.tmpl
```
**In alertmanager URL**

![image](https://user-images.githubusercontent.com/25129744/220335471-f8b7295f-dacd-4cd1-8d2a-da9106b9ffb3.png)

Now I want to reciver those alerts in a snmp trap server.
So I have installed snmp_notifier with latest image.
**SNMP notifier command line:**
```
- /bin/snmp_notifier
        - --snmp.trap-description-template=/etc/snmp_notifier/description-template.tpl
        - --log.level=debug
        - --alert.severities="emergency,high,medium,low,critical,warning,info"
        - --alert.default-severity="high"
        - --snmp.destination=10.0.113.233:162
        - --snmp.version=V3
        - --snmp.authentication-enabled
        - --snmp.authentication-protocol=SHA
        - --snmp.authentication-username=snmp_user_v3
        - --snmp.authentication-password=auth_password_v3
        - --snmp.private-enabled
        - --snmp.private-protocol=AES
        - --snmp.private-password=encrypt_password_v3
        - --snmp.context-engine-id=0x8000000001020304
```
 I have added some custom severities as per my PrometheusRule setup

In ```--snmp.destination``` I added the IP of the snmp-server service.
Which I installed in same namespace using your given example [https://github.com/maxwo/snmp_notifier/blob/main/scripts/kubernetes/snmp-server.yaml](https://github.com/maxwo/snmp_notifier/blob/main/scripts/kubernetes/snmp-server.yaml) without any change in given yaml.

In snmp_notifier pod log getting 200 in response, though requesting header not showing

```192.168.216.59 - - [21/Feb/2023:11:15:00 +0000] "POST /alerts HTTP/1.1" 200 0
ts=2023-02-21T11:15:14.994Z caller=http_server.go:78 level=debug msg="Handling /alerts webhook request"
ts=2023-02-21T11:15:14.994Z caller=http_server.go:78 level=debug msg="Handling /alerts webhook request"
ts=2023-02-21T11:15:14.995Z caller=http_server.go:78 level=debug msg="Handling /alerts webhook request"
ts=2023-02-21T11:15:15.006Z caller=http_server.go:78 level=debug msg="Handling /alerts webhook request"
192.168.216.59 - - [21/Feb/2023:11:15:14 +0000] "POST /alerts HTTP/1.1" 200 0
192.168.216.59 - - [21/Feb/2023:11:15:14 +0000] "POST /alerts HTTP/1.1" 200 0
192.168.216.59 - - [21/Feb/2023:11:15:14 +0000] "POST /alerts HTTP/1.1" 200 0
192.168.216.59 - - [21/Feb/2023:11:15:15 +0000] "POST /alerts HTTP/1.1" 200 0
```
But in snmp-server nothing is coming

***kubectl logs of snmp-server***
```
NET-SNMP version 5.9.3
```

**What did you expect to see?**
I am expecting the trap details to be shown in snmp-server logs, also in snmp notifier logs.

**Environment**
Bare metal K8s cluster, kubernetes version 1.25

* System information:

       `Linux 4.18.0-372.9.1.el8.x86_64 x86_64`

* SNMP notifier version:

	`1.4.0`

* Alertmanager version:

	`0.23.0`

* Alertmanager command line:
```
/bin/alertmanager --config.file=/etc/alertmanager/config/alertmanager.yaml --storage.path=/alertmanager --data.retention=120h --cluster.listen-address= --web.listen-address=:9093 --web.external-url=http://cnp-sandbox-kube-prometheu-alertmanager.cnp-monitoring:9093 --web.route-prefix=/ --cluster.peer=alertmanager-cnp-sandbox-kube-prometheu-alertmanager-0.alertmanager-operated:9094 --cluster.reconnect-timeout=5m
```

**Comment by maxwo** [comment] 2023-02-21 19:06
Actually, I managed to reproduce using your exact command-line. Haven't noticed it, but you should not add the leading `0x` from the engine IDs:

```
        - --snmp.context-engine-id=8000000001020304
        - --snmp.security-engine-id=8000000001020304
```

**Comment by sanupanji** [comment] 2023-02-24 07:04
Thank @maxwo its working now, I can see the traps in snmp server.
But 2 things:
1.  First custom severity still not working, I need to add dummy severity in 1st index to make it work (in this case "dummy")
```
  - --alert.severities="dummy,critical,high,medium,low,warning,info"
  ```
2. Why snmp notifier log not showing what I am requesting to snmp server. Its only showing
```
192.168.216.59 - - [21/Feb/2023:11:15:14 +0000] "POST /alerts HTTP/1.1" 200 0
```
Logs should include the full header and description.

**Comment by maxwo** [comment] 2023-02-25 14:27
About your points:

1. You must have some `dummy` alert severities somewhere in your prometheus alert configurations. It may be a good idea to add a default severity when it does not match any of the declared severities though.
2. The logs are intended to display access logs. I may add some extra informations when in debug mode.

Can you create the corresponding issues?

**Comment by sanupanji** [comment] 2023-02-28 07:03
I have only below severities 
```
critical,high,medium,low,warning,info
```
But the first value I am passing in ```  - --alert.severities="critical,high,medium,low,warning,info"``` is not picked up by notifier
Getting below error in logs:

```
ts=2023-02-28T06:56:00.111Z caller=http_server.go:132 level=error status=400 statustext="Bad Request" err="incorrect severity: critical" data="unsupported value type"
```

so I am adding "dummy" in the first position as a workaround
```
  - --alert.severities="dummy,critical,high,medium,low,warning,info"
```

**Comment by maxwo** [comment] 2023-03-05 15:09
Can you try sending these alerts:

```json
{
  "receiver": "snmp-notifier",
  "status": "firing",
  "groupLabels": {
    "environment": "production",
    "label": "test"
  },
  "alerts": [
    {
      "status": "firing",
      "labels": {
        "severity": "warning",
        "alertname": "TestAlert",
        "oid": "1.3.6.1.4.1.666.0.10.1.1.1.2.1"
      },
      "annotations": {
        "summary": "this is the random summary",
        "description": "this is the description of alert 1"
      }
    },
    {
      "status": "resolved",
      "labels": {
        "severity": "warning",
        "alertname": "TestAlert",
        "oid": "1.3.6.1.4.1.666.0.10.1.1.1.1.1"
      },
      "annotations": {
        "summary": "this is the random summary",
        "description": "this is the description of ActiveMQ alert"
      }
    },
    {
      "status": "firing",
      "labels": {
        "severity": "critical",
        "alertname": "TestAlert",
        "oid": "1.3.6.1.4.1.666.0.10.1.1.1.2.1"
      },
      "annotations": {
        "summary": "this is the summary",
        "description": "this is the description on job1"
      }
    },
    {
      "status": "resolved",
      "labels": {
        "severity": "critical",
        "alertname": "TestAlert",
        "oid": "1.3.6.1.4.1.666.0.10.1.1.1.2.1"
      },
      "annotations": {
        "summary": "this is the summary",
        "description": "this is the description on TestAlertWithoutOID"
      }
    }
  ]
}
```

Thanks to such a command: `curl -XPOST http://localhost:9464/alerts -H 'Content-Type: application/json' --data '@alerts.json'` ?

I successfully received them with no error and this command line:

```
./snmp_notifier         --log.level=debug \
         --alert.severities="critical,high,medium,low,warning,info" \
         --alert.default-severity="high" \
         --snmp.version=V3 \
         --snmp.authentication-enabled \
         --snmp.authentication-protocol=SHA \
         --snmp.authentication-username=snmp_user_v3 \
         --snmp.authentication-password=auth_password_v3  \
         --snmp.private-enabled \
         --snmp.private-protocol=AES \
         --snmp.private-password=encrypt_password_v3 \
         --snmp.security-engine-id=8000000001020304 --snmp.context-name=''
```

Which should look a lot like yours.

**Comment by pknee** [comment] 2023-03-21 09:51
Hi!

I have a similar behavior as @sanupanji regarding the severities. Since it's deployed on Openshift 4.10 and ocp does implement the watchdog/dead man's switch with severity "none" I need to extend the severites.

This configuration 
```
command:
            - /bin/snmp_notifier
            - >-
              --snmp.trap-description-template=/etc/snmp_notifier/description-template.tpl
            - '--snmp.destination=192.168.1.1:162'
            - '--web.listen-address=:8080'
            - '--alert.severities="critical,warning,info,none"' # <
            - '--log.level=debug'

```
throws errors as soon as a critical alert is raised

> s=2023-03-21T09:43:22.386Z caller=http_server.go:132 level=error status=400 statustext="Bad Request" err="incorrect severity: critical" data="unsupported value type"

Adding the dummy resolved the issue:
`- '--alert.severities="dummy,critical,warning,info,none"'`


Best regars
Philip

**Comment by maxwo** [comment] 2023-03-26 09:14
I think the problem comes from the command-line itself:

```
- '--alert.severities="critical,warning,info,none"'
```

Leads to the following severity list:

```
["emergency high medium low critical warning info"]
```

`--alert.severities="critical,warning,info,none"`, without the leading quotes, seems to correctly parse the value, as well as `'--alert.severities=critical,warning,info,none'`.

Can you confirm that?

**Comment by adalberto-almeida-pereira-alb** [comment] 2023-08-18 18:35
Hi @maxwo  I hope you are doing well. May you help me please?

I have done this configuration to receive snmptraps and send them to snmp-server.

If I use curl with your alerts.json file above, I am able to see the logs in snmp-server, but I can`t receive this alerts in alertmanager.

Both, alert manager and snmp-notifer are in the same namespace

My alertmanager conf:

`global:
  resolve_timeout: 5m
  http_config: {}
  smtp_hello: localhost
  smtp_require_tls: true
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
route:
  receiver: default
  group_by:
  - job
  routes:
  - receiver: snmp_notifier
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 15m
receivers:
- name: default
  webhook_configs:
  - send_resolved: true
    http_config: {}
    url: http://alarmmgr-padapter-http-gateway.123test.svc.cluster.local:8080/api/event
    max_alerts: 30
- name: snmp_notifier
  webhook_configs:
  - send_resolved: true
    http_config: {}
    url: http://snmp-notifier.123test.svc.cluster.local:9464/alerts
    max_alerts: 0
templates: []`

**Comment by maxwo** [comment] 2023-10-15 18:55
Closing, as there is no more answers, and a solution has been found.

**Closed by maxwo** 2023-10-15 18:55 UTC

**Comment by lianghuiyuan** [comment] 2024-06-11 13:24
> Closing, as there is no more answers, and a solution has been found.

Sorry, What's the solution?

This is my configration:
```
    command:
        - --web.listen-address=:9464
        - --alert.severity-label="severity"                         # Label where to find the alert severity.
        - '--alert.severities="emergency,alert,error,critical,warning,notification,informational"'                # The ordered list of alert severities, from more priority to less priority. 级别： emergency(1) alert(2) error(3) critical(4) warning(5) notification(6) informational(7)
        - --alert.default-severity="warning"                        # The alert severity if none is provided via labels.
        - --snmp.version=V2c                                        # SNMP version. V2c and V3 are currently supported.
        - --snmp.trap-oid-label=oid                                 # Label where to find the trap OID.
        - --snmp.trap-default-oid=1.3.6.1.4.1.58199                 # Trap OID to send if none is found in the alert labels.
        - --snmp.destination=127.0.0.1:162                          # SNMP trap server destination.
        - --snmp.timeout=5s                                         # SNMP timeout duration
        - --snmp.retries=1                                          # SNMP number of retries
        - --snmp.trap-description-template=/etc/snmp_notifier/description-template.tpl         # SNMP trap description template
        - --snmp.community="public"                                 # SNMP community (V2c only). Passing secrets to the command line is not recommended, consider using the SNMP_NOTIFIER_COMMUNITY environment variable instead. ($SNMP_NOTIFIER_COMMUNITY)
        - --log.level=info                                          # Only log messages with the given severity or above. One of: [debug, info, warn, error]
        - --log.format=logfmt                                       # Output format of log messages. One of: [logfmt, json]
```

errors:
````
# docker logs -f snmp-notifier
ts=2024-06-11T13:19:41.500Z caller=tls_config.go:274 level=info msg="Listening on" address=[::]:9464
ts=2024-06-11T13:19:41.500Z caller=tls_config.go:277 level=info msg="TLS is disabled." http2=false address=[::]:9464
ts=2024-06-11T13:19:48.101Z caller=http_server.go:147 level=error status=422 statustext="Unprocessable Entity" err=EOF data="unsupported value type"
ts=2024-06-11T13:19:52.229Z caller=http_server.go:147 level=error status=400 statustext="Bad Request" err="incorrect severity: \"warning\"" data="unsupported value type"
ts=2024-06-11T13:19:52.584Z caller=http_server.go:147 level=error status=422 statustext="Unprocessable Entity" err=EOF data="unsupported value type"
ts=2024-06-11T13:21:52.190Z caller=http_server.go:147 level=error status=400 statustext="Bad Request" err="incorrect severity: \"warning\"" data="unsupported value type"
ts=2024-06-11T13:21:52.190Z caller=http_server.go:147 level=error status=400 statustext="Bad Request" err="incorrect severity: \"warning\"" data="unsupported value type"
ts=2024-06-11T13:21:52.190Z caller=http_server.go:147 level=error status=400 statustext="Bad Request" err="incorrect severity: \"warning\"" data="unsupported value type"
ts=2024-06-11T13:21:52.190Z caller=http_server.go:147 level=error status=400 statustext="Bad Request" err="incorrect severity: \"warning\"" data="unsupported value type"
ts=2024-06-11T13:21:52.190Z caller=http_server.go:147 level=error status=400 statustext="Bad Request" err="incorrect severity: \"warning\"" data="unsupported value type"
ts=2024-06-11T13:21:52.190Z caller=http_server.go:147 level=error status=400 statustext="Bad Request" err="incorrect severity: \"warning\"" data="unsupported value type"
ts=2024-06-11T13:21:52.190Z caller=http_server.go:147 level=error status=400 statustext="Bad Request" err="incorrect severity: \"warning\"" data="unsupported value type"
ts=2024-06-11T13:21:52.190Z caller=http_server.go:147 level=error status=400 statustext="Bad Request" err="incorrect severity: \"warning\"" data="unsupported value type"
ts=2024-06-11T13:21:52.190Z caller=http_server.go:147 level=error status=400 statustext="Bad Request" err="incorrect severity: \"warning\"" data="unsupported value type"
ts=2024-06-11T13:21:52.190Z caller=http_server.go:147 level=error status=400 statustext="Bad Request" err="incorrect severity: \"warning\"" data="unsupported value type"
ts=2024-06-11T13:21:52.190Z caller=http_server.go:147 level=error status=400 statustext="Bad Request" err="incorrect severity: \"warning\"" data="unsupported value type"
```
